# Patch generated by Pyment v0.3.3

--- a/..//venv/lib/python3.8/site-packages/pandas/tests/util/test_validate_args.py
+++ b/..//venv/lib/python3.8/site-packages/pandas/tests/util/test_validate_args.py
@@ -6,6 +6,7 @@
 
 
 def test_bad_min_fname_arg_count():
+    """ """
     msg = "'max_fname_arg_count' must be non-negative"
 
     with pytest.raises(ValueError, match=msg):
@@ -13,6 +14,7 @@
 
 
 def test_bad_arg_length_max_value_single():
+    """ """
     args = (None, None)
     compat_args = ("foo",)
 
@@ -29,6 +31,7 @@
 
 
 def test_bad_arg_length_max_value_multiple():
+    """ """
     args = (None, None)
     compat_args = dict(foo=None)
 
@@ -46,6 +49,17 @@
 
 @pytest.mark.parametrize("i", range(1, 3))
 def test_not_all_defaults(i):
+    """
+
+    Parameters
+    ----------
+    i :
+        
+
+    Returns
+    -------
+
+    """
     bad_arg = "foo"
     msg = (
         f"the '{bad_arg}' parameter is not supported "
@@ -60,6 +74,7 @@
 
 
 def test_validation():
+    """ """
     # No exceptions should be raised.
     validate_args(_fname, (None,), 2, dict(out=None))
 
