# Patch generated by Pyment v0.3.3

--- a/..//venv/lib/python3.8/site-packages/pandas/tests/indexes/multi/test_take.py
+++ b/..//venv/lib/python3.8/site-packages/pandas/tests/indexes/multi/test_take.py
@@ -6,6 +6,17 @@
 
 
 def test_take(idx):
+    """
+
+    Parameters
+    ----------
+    idx :
+        
+
+    Returns
+    -------
+
+    """
     indexer = [4, 3, 0, 2]
     result = idx.take(indexer)
     expected = idx[indexer]
@@ -18,6 +29,17 @@
 
 
 def test_take_invalid_kwargs(idx):
+    """
+
+    Parameters
+    ----------
+    idx :
+        
+
+    Returns
+    -------
+
+    """
     idx = idx
     indices = [1, 2]
 
@@ -35,6 +57,7 @@
 
 
 def test_take_fill_value():
+    """ """
     # GH 12631
     vals = [["A", "B"], [pd.Timestamp("2011-01-01"), pd.Timestamp("2011-01-02")]]
     idx = pd.MultiIndex.from_product(vals, names=["str", "dt"])
